---

apiVersion: batch/v1
kind: "job"
metadata:
  name: "{{ meta.name }}-sysbench"
  namespace: "{{ meta.namespace }}"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
       app: sysbench
    spec:
      containers:
      - name: sysbench
        command: ["/bin/sh", "-c"]
        args: ["/tmp/sysbenchScript"]
        image: "docker.io/smalleni/centos-sysbench:latest"
        volumeMounts:
        - name: sysbench-volume
          mountPath: "/tmp/"
{% if store_results %}
        - name: result-data
          mountPath: "{{results.path}}"
{% endif %}
      volumes:
      - name: sysbench-volume
        configMap:
          name: "{{ meta.name }}-sysbench-config"
          defaultMode: 0777
{% if store_results %}
      - name: result-data
        persistentVolumeClaim:
          claimName: result-volume
{% endif %}
      restartPolicy: OnFailure
